/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pqbSBZb9VG36A9gA4GgWPg
// Component: ceoSk4_Tn_gI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: tGuDlEY_p2-T/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { Iframe } from "@plasmicpkgs/plasmic-basic-components";
import ChunkyButton from "../../ChunkyButton"; // plasmic-import: afhvlQtgWcWV/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../liz_website/plasmic.module.css"; // plasmic-import: pqbSBZb9VG36A9gA4GgWPg/projectcss
import sty from "./PlasmicGuestbook.module.css"; // plasmic-import: ceoSk4_Tn_gI/css

createPlasmicElementProxy;

export type PlasmicGuestbook__VariantMembers = {};
export type PlasmicGuestbook__VariantsArgs = {};
type VariantPropType = keyof PlasmicGuestbook__VariantsArgs;
export const PlasmicGuestbook__VariantProps = new Array<VariantPropType>();

export type PlasmicGuestbook__ArgsType = {};
type ArgPropType = keyof PlasmicGuestbook__ArgsType;
export const PlasmicGuestbook__ArgProps = new Array<ArgPropType>();

export type PlasmicGuestbook__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  reveal?: Flex__<typeof Reveal>;
  text?: Flex__<"div">;
  iframe?: Flex__<typeof Iframe>;
  columns?: Flex__<"div">;
  sliderCarousel2?: Flex__<typeof SliderWrapper>;
};

export interface DefaultGuestbookProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGuestbook__RenderFunc(props: {
  variants: PlasmicGuestbook__VariantsArgs;
  args: PlasmicGuestbook__ArgsType;
  overrides: PlasmicGuestbook__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicGuestbook.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicGuestbook.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicGuestbook.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <Navbar
          data-plasmic-name={"navbar"}
          data-plasmic-override={overrides.navbar}
          className={classNames("__wab_instance", sty.navbar)}
        />

        <Reveal
          data-plasmic-name={"reveal"}
          data-plasmic-override={overrides.reveal}
          cascade={false}
          className={classNames("__wab_instance", sty.reveal)}
          reverse={false}
          triggerOnce={true}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__rgjpF)}
          >
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"The Guestbook"}
                </span>
              </React.Fragment>
            </div>
            <Iframe
              data-plasmic-name={"iframe"}
              data-plasmic-override={overrides.iframe}
              className={classNames("__wab_instance", sty.iframe)}
              src={"https://honeyteaaa.atabook.org"}
              srcDoc={"<div><h3>Heading</h3><p>Example text...</p></div>"}
              useHtml={false}
            />

            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column___99Afw)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___59Saf)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateSliderCarouselCurrentSlide"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["sliderCarousel2", "currentSlide"]
                            },
                            operation: 3
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = $stateGet(objRoot, variablePath);
                            $stateSet(objRoot, variablePath, oldValue - 1);
                            return oldValue - 1;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateSliderCarouselCurrentSlide"] != null &&
                      typeof $steps["updateSliderCarouselCurrentSlide"] ===
                        "object" &&
                      typeof $steps["updateSliderCarouselCurrentSlide"].then ===
                        "function"
                    ) {
                      $steps["updateSliderCarouselCurrentSlide"] = await $steps[
                        "updateSliderCarouselCurrentSlide"
                      ];
                    }
                  }}
                >
                  <ChunkyButton
                    className={classNames(
                      "__wab_instance",
                      sty.chunkyButton___4VQmZ
                    )}
                    text={"<"}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__my4X)} />

              <div className={classNames(projectcss.all, sty.column__bYnMh)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__o0Rf0)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateSliderCarouselCurrentSlide"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["sliderCarousel2", "currentSlide"]
                            },
                            operation: 2
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = $stateGet(objRoot, variablePath);
                            $stateSet(objRoot, variablePath, oldValue + 1);
                            return oldValue + 1;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateSliderCarouselCurrentSlide"] != null &&
                      typeof $steps["updateSliderCarouselCurrentSlide"] ===
                        "object" &&
                      typeof $steps["updateSliderCarouselCurrentSlide"].then ===
                        "function"
                    ) {
                      $steps["updateSliderCarouselCurrentSlide"] = await $steps[
                        "updateSliderCarouselCurrentSlide"
                      ];
                    }
                  }}
                >
                  <ChunkyButton
                    className={classNames(
                      "__wab_instance",
                      sty.chunkyButton___6AeSt
                    )}
                    text={">"}
                  />
                </div>
              </div>
            </div>
            {(() => {
              const child$Props = {
                arrowColor: true ? "#331009" : undefined,
                arrows: true,
                autoplay: false,
                autoplaySpeed: 0,
                beforeChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "currentSlide",
                    ["sliderCarousel2", "currentSlide"],
                    SliderWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                centerMode: false,
                children: null,
                className: classNames("__wab_instance", sty.sliderCarousel2),
                cssEase: "ease-in-out",
                dots: false,
                fade: true,
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel2",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel2"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel2__slider"],
                speed: 250,
                useCSS: true,
                vertical: false
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel2.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel2"}
                  data-plasmic-override={overrides.sliderCarousel2}
                  {...child$Props}
                />
              );
            })()}
          </Stack__>
        </Reveal>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "reveal",
    "text",
    "iframe",
    "columns",
    "sliderCarousel2"
  ],
  navbar: ["navbar"],
  reveal: ["reveal", "text", "iframe", "columns", "sliderCarousel2"],
  text: ["text"],
  iframe: ["iframe"],
  columns: ["columns"],
  sliderCarousel2: ["sliderCarousel2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  reveal: typeof Reveal;
  text: "div";
  iframe: typeof Iframe;
  columns: "div";
  sliderCarousel2: typeof SliderWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGuestbook__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGuestbook__VariantsArgs;
    args?: PlasmicGuestbook__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGuestbook__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicGuestbook__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGuestbook__ArgProps,
          internalVariantPropNames: PlasmicGuestbook__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGuestbook__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGuestbook";
  } else {
    func.displayName = `PlasmicGuestbook.${nodeName}`;
  }
  return func;
}

export const PlasmicGuestbook = Object.assign(
  // Top-level PlasmicGuestbook renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    reveal: makeNodeComponent("reveal"),
    text: makeNodeComponent("text"),
    iframe: makeNodeComponent("iframe"),
    columns: makeNodeComponent("columns"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),

    // Metadata about props expected for PlasmicGuestbook
    internalVariantProps: PlasmicGuestbook__VariantProps,
    internalArgProps: PlasmicGuestbook__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Bee More Info",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicGuestbook;
/* prettier-ignore-end */
