// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pqbSBZb9VG36A9gA4GgWPg
// Component: DT1TBfZUYTUH

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: pqbSBZb9VG36A9gA4GgWPg/projectcss
import sty from "./PlasmicCardFlipTest.module.css"; // plasmic-import: DT1TBfZUYTUH/css

createPlasmicElementProxy;

export type PlasmicCardFlipTest__VariantMembers = {
  flipped: "flipped";
};
export type PlasmicCardFlipTest__VariantsArgs = {
  flipped?: SingleBooleanChoiceArg<"flipped">;
};
type VariantPropType = keyof PlasmicCardFlipTest__VariantsArgs;
export const PlasmicCardFlipTest__VariantProps = new Array<VariantPropType>(
  "flipped"
);

export type PlasmicCardFlipTest__ArgsType = {};
type ArgPropType = keyof PlasmicCardFlipTest__ArgsType;
export const PlasmicCardFlipTest__ArgProps = new Array<ArgPropType>();

export type PlasmicCardFlipTest__OverridesType = {
  root?: Flex__<"div">;
  front?: Flex__<"div">;
  front2?: Flex__<"div">;
};

export interface DefaultCardFlipTestProps {
  flipped?: SingleBooleanChoiceArg<"flipped">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardFlipTest__RenderFunc(props: {
  variants: PlasmicCardFlipTest__VariantsArgs;
  args: PlasmicCardFlipTest__ArgsType;
  overrides: PlasmicCardFlipTest__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "flipped",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.flipped
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootflipped]: hasVariant($state, "flipped", "flipped") }
      )}
      onClick={async event => {
        const $steps = {};

        $steps["updateFlipped"] = true
          ? (() => {
              const actionArgs = {
                vgroup: "flipped",
                operation: 2,
                value: "flipped"
              };
              return (({ vgroup, value }) => {
                if (typeof value === "string") {
                  value = [value];
                }

                const oldValue = $stateGet($state, vgroup);
                $stateSet($state, vgroup, !oldValue);
                return !oldValue;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateFlipped"] != null &&
          typeof $steps["updateFlipped"] === "object" &&
          typeof $steps["updateFlipped"].then === "function"
        ) {
          $steps["updateFlipped"] = await $steps["updateFlipped"];
        }
      }}
    >
      <div
        data-plasmic-name={"front"}
        data-plasmic-override={overrides.front}
        className={classNames(projectcss.all, sty.front, {
          [sty.frontflipped]: hasVariant($state, "flipped", "flipped")
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__uiyxM
          )}
        >
          {"Front"}
        </div>
      </div>
      <div
        data-plasmic-name={"front2"}
        data-plasmic-override={overrides.front2}
        className={classNames(projectcss.all, sty.front2, {
          [sty.front2flipped]: hasVariant($state, "flipped", "flipped")
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__izOg
          )}
        >
          {"Front"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "front", "front2"],
  front: ["front"],
  front2: ["front2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  front: "div";
  front2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardFlipTest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardFlipTest__VariantsArgs;
    args?: PlasmicCardFlipTest__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCardFlipTest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCardFlipTest__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardFlipTest__ArgProps,
          internalVariantPropNames: PlasmicCardFlipTest__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardFlipTest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardFlipTest";
  } else {
    func.displayName = `PlasmicCardFlipTest.${nodeName}`;
  }
  return func;
}

export const PlasmicCardFlipTest = Object.assign(
  // Top-level PlasmicCardFlipTest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    front: makeNodeComponent("front"),
    front2: makeNodeComponent("front2"),

    // Metadata about props expected for PlasmicCardFlipTest
    internalVariantProps: PlasmicCardFlipTest__VariantProps,
    internalArgProps: PlasmicCardFlipTest__ArgProps
  }
);

export default PlasmicCardFlipTest;
/* prettier-ignore-end */
