/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pqbSBZb9VG36A9gA4GgWPg
// Component: UbQJeS6FBfv3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: tGuDlEY_p2-T/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Polaroid from "../../Polaroid"; // plasmic-import: SGzL5zPyMcua/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: pqbSBZb9VG36A9gA4GgWPg/projectcss
import sty from "./PlasmicAboutMe2.module.css"; // plasmic-import: UbQJeS6FBfv3/css

createPlasmicElementProxy;

export type PlasmicAboutMe2__VariantMembers = {};
export type PlasmicAboutMe2__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutMe2__VariantsArgs;
export const PlasmicAboutMe2__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutMe2__ArgsType = {};
type ArgPropType = keyof PlasmicAboutMe2__ArgsType;
export const PlasmicAboutMe2__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutMe2__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  reveal?: Flex__<typeof Reveal>;
};

export interface DefaultAboutMe2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutMe2__RenderFunc(props: {
  variants: PlasmicAboutMe2__VariantsArgs;
  args: PlasmicAboutMe2__ArgsType;
  overrides: PlasmicAboutMe2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <Reveal
            data-plasmic-name={"reveal"}
            data-plasmic-override={overrides.reveal}
            cascade={false}
            className={classNames("__wab_instance", sty.reveal)}
            triggerOnce={true}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__eimxq)}
            >
              <div className={classNames(projectcss.all, sty.column___63Ant)}>
                <Polaroid
                  backHeader1={"Photo By:"}
                  className={classNames("__wab_instance", sty.polaroid__fmyP4)}
                  date2={``}
                  infoPage={"https://liamlyonsiv.myportfolio.com"}
                  projectTitle={``}
                  slot={"Liam Lyons"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__t0MLg)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/liz_website/images/lizManzImmHeadshots002Jpg.jpg",
                      fullWidth: 3439,
                      fullHeight: 5158,
                      aspectRatio: undefined
                    }}
                  />
                </Polaroid>
              </div>
              <div className={classNames(projectcss.all, sty.column__jizmb)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rnn7N)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yO8Vl
                    )}
                  >
                    {"About Me.*"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h2TOh
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "I'm Tea, a multidisciplinary digital artist and full time college student. I make art in Blender, VRChat Avatars, games in Unity Engine, and love to learn new software.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"Expand this"}
                      </span>
                    </React.Fragment>
                  </div>
                </Stack__>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__zMPf)}
            >
              <div className={classNames(projectcss.all, sty.column__bFy1C)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___9O4Ic)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h3O3L
                    )}
                  >
                    {"What I Do.*"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2TG2
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "Idk talk about what art i do and what hobbies i have\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"Balisong Photo by ang?"}
                      </span>
                    </React.Fragment>
                  </div>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__xNRtC)}>
                <Polaroid
                  backHeader1={"Photo By:"}
                  className={classNames("__wab_instance", sty.polaroid___3FWiv)}
                  date2={``}
                  infoPage={"https://www.disuko.gay"}
                  projectTitle={``}
                  slot={"Disuko"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2OvFj)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/liz_website/images/img1583Jpg.jpg",
                      fullWidth: 2316,
                      fullHeight: 3088,
                      aspectRatio: undefined
                    }}
                  />
                </Polaroid>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xaFvO)}
            >
              <div className={classNames(projectcss.all, sty.column__wAlqK)}>
                <Polaroid
                  backHeader1={"Photo By:"}
                  className={classNames("__wab_instance", sty.polaroid___6RjEr)}
                  date2={``}
                  infoPage={"https://www.disuko.gay"}
                  projectTitle={``}
                  slot={"Disuko"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ivqWw)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/liz_website/images/vrChat202412192339314551920X1080Png.png",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />
                </Polaroid>
              </div>
              <div className={classNames(projectcss.all, sty.column__iQdsI)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tn0Cm)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__soUbL
                    )}
                  >
                    {"ETC.*"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pRxVa
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {
                          "Fun facts about me or something idk, threes look better than two blocks D:"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {
                          "Maybe talk about how i started as a VRChat creator or somethin?"
                        }
                      </span>
                    </React.Fragment>
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </Reveal>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "reveal"],
  navbar: ["navbar"],
  reveal: ["reveal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  reveal: typeof Reveal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutMe2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutMe2__VariantsArgs;
    args?: PlasmicAboutMe2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutMe2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAboutMe2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutMe2__ArgProps,
          internalVariantPropNames: PlasmicAboutMe2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutMe2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutMe2";
  } else {
    func.displayName = `PlasmicAboutMe2.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutMe2 = Object.assign(
  // Top-level PlasmicAboutMe2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    reveal: makeNodeComponent("reveal"),

    // Metadata about props expected for PlasmicAboutMe2
    internalVariantProps: PlasmicAboutMe2__VariantProps,
    internalArgProps: PlasmicAboutMe2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutMe2;
/* prettier-ignore-end */
